### ISSUE TITLE
demo: "Error creating account!"

### ISSUE THREAD

**Issue by hex-m** [Y0ngg4n/fluffy_board#30]
I get an error when I try to register an account on the [demo instance](https://fluffyboard.obco.pro/). It says nothing specific so I have no idea what went wrong.

**Comment by Y0ngg4n** [comment]
@hex-m currently i am making server Migrations so the database is possibly down.

**Comment by almereyda** [comment]
I had the same errors today, and were given CORS as a reason:

![Bildschirmfoto von 2022-02-04 22-06-56](https://user-images.githubusercontent.com/1645308/152603218-2caa955e-ed4a-4af8-9411-8c981f74f017.png)

**Comment by Y0ngg4n** [comment]
@almereyda it is because the server is currently down because i am migrating it to kubernetes

**Comment by almereyda** [comment]
Cool, we have good timing here catching the demo in constant
migration. Glad there is active maintenance on the deal.

Fluffyboard is the only "Whiteboard" application in F-Droid to date,
as per the search term.

**Comment by Y0ngg4n** [comment]
@almereyda sorry i think it will take about a month to fully migrate my server to the kubernetes setup. I know it is not great. But i am maintaining everything in my spare time while studying. It you want you can setup your own server with that repo:
https://github.com/Y0ngg4n/fluffy_rest_api
I will add Helm Charts to this Repo when i am finished with migration. 
Thank you for your patience. I will give my best :sweat_smile:

**Comment by almereyda** [comment]
Thank you very much for the pointer! Self-hosting was indeed my primary target, and I will see how far this gets us. Always happy to help out with testing things, etc.

**Comment by Y0ngg4n** [comment]
@almereyda if you have questions how to set it up don´t hestitate to ask. Currently on fdroid is release 11 because i haven´t had time yet to fix auto update in fdroid. Till then you can use the 12 Release from the releases page here on github :)

**Comment by almereyda** [comment]
That's good to know ;)

**Comment by Y0ngg4n** [comment]
@almereyda @hex-m Server should be back online again :)
As i found out i didn´t managed to get fluffyboard working in kubernetes because scylladb does not like nfs shares. So it is currently running on my docker server.

**Comment by almereyda** [comment]
Many thanks for the effort! This worked, so from my side feel free to close here ^_^
