### ISSUE TITLE
Fluffyboard taking a nap

### ISSUE THREAD

**Issue by almereyda** [Y0ngg4n/fluffy_board#31]
As a recurrence of #26, we currently find https://fluffyboard.obco.pro/ to display `Bad Gateway`.

**Comment by Y0ngg4n** [comment]
@almereyda 
![image](https://user-images.githubusercontent.com/30302975/171651151-7b124704-ed3c-4327-be63-caa9d652efc1.png)

**Comment by almereyda** [comment]
Ah, ok. Please pardon the interruption (: I hadn't noticed this was updated in the repository, and used the link from my bookmarks.

Should we close here then?

**Comment by Y0ngg4n** [comment]
@almereyda yes no problem. I am looking forward to host a demo soon and refactor the project. but currently i am limited in time.

**Comment by Y0ngg4n** [comment]
@almereyda maybe test it again. I think i deployed the rest api again on my server.

**Comment by almereyda** [comment]
Thank you!

> Interestingly, that email response was sent on July the 3rd, and only appeared here now. How many issue responses might have been delayed or lost that way already throughout all of GitHub?
