### ISSUE TITLE
"Error creating account!"

### ISSUE THREAD

**Issue by jegarfa** [Y0ngg4n/fluffy_board#32]
Hi, I am new in Fluffyboard. I am trying it on Android and on Linux. In both cases I got "Error creating account" when I tried to register. Any suggestion? Any help would be greatly appreciated.

**Comment by Y0ngg4n** [comment]
Currently there is no server setup. You can host your own server with https://github.com/Y0ngg4n/fluffy_rest_api

**Comment by jegarfa** [comment]
thanks! could you please give some details/instructions on how to seting it up in dockerhub? I already have an account but I have not deploy a project with docker.

**Comment by Y0ngg4n** [comment]
@jegarfa you don´t need to create a dockerhub account. Please read the readme in the fluffy_rest_api repo first. 
There is this docker-compose linked: https://github.com/Y0ngg4n/fluffy_rest_api/blob/master/docker-compose.yml
There is tons of documentation on how to spin up docker containers with docker compose on the internet
